# Config file for DoorCloser

# Time (in integer seconds) to allow the door to remain open
Time: 20

# true if you want to ignore the door opening when the player is in creative mode
IgnoreIfInCreative: true

# true if you want to ignore the door opening when the player is sneaking
IgnoreIfSneaking: false

# List of Block IDs for blocks (trap doors, gates, and doors) that you want to auto-close
# Case is not important, but use the official block names as found here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
TrapDoorBlocks:
- trap_door

GateBlocks:
- fence_gate
- spruce_fence_gate
- birch_fence_gate
- jungle_fence_gate
- dark_oak_fence_gate
- acacia_fence_gate

DoorBlocks:
- wooden_door
- spruce_door
- birch_door
- jungle_door
- acacia_door
- dark_oak_door



