# Config file for DoorCloser

# Time (in integer seconds) to allow the door to remain open
Time: 10

# double-door handling. This is a bit outside the original scope
# of this plugin, but was a community request. It's optional here
# because you may already have plugins handling this, and so the
# behavior might be weird.
#
# SynchronizeDoubleDoorOpen: automatically open the second door
# when you click on one of the doors in a pair. Detection algorithm
# checks for where the hinges are located.
SynchronizeDoubleDoorOpen: true
SynchronizeDoubleDoorClose: true

# True if the door/gate/trapdoor closing sound should be played
PlaySound: true

# true if you want to ignore the door when the player is in creative mode
# if this is not set to true, you'll never be able to create an open door
# unless you turn on sneaking.
IgnoreIfInCreative: true

# true if you want to ignore the door when the player is sneaking
# note that this will work for all players, not just someone in creative
IgnoreIfSneaking: false

# List of Block IDs for blocks (trap doors, gates, and doors) that you want to auto-close
# Case is not important, but use the official block names as found here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
TrapDoorBlocks:
- acacia_trapdoor
- birch_trapdoor
- dark_oak_trapdoor
- jungle_trapdoor
- oak_trapdoor
- spruce_trapdoor

GateBlocks:
- oak_fence_gate
- spruce_fence_gate
- birch_fence_gate
- jungle_fence_gate
- dark_oak_fence_gate
- acacia_fence_gate

DoorBlocks:
- oak_door
- spruce_door
- birch_door
- jungle_door
- acacia_door
- dark_oak_door




