name: DoorCloser
main: net.tenrem.doorcloser.DoorCloserPlugin
version: 1.1.0
api-version: 1.13
author: Pete Brown 10rem.net
commands:
   dcreload:
      description: Reload the configuration file.
      usage: "Usage: '/dcreload' to reload configuration file."
      permission: tenrem.doorcloser.reload
      permission-message: You don't have permission to reload the configuration file.
   
   